development:
  adapter: mysql2
  encoding: utf8
  database: skillpark_development
  host: localhost
  username: root
  password:

test:
  adapter: mysql2
  encoding: utf8
  database: skillpark_test
  host: localhost
  username: root
  password:

production:
  adapter: mysql2
  encoding: utf8
  database: skillpark_production
  host: localhost
  username: root
  password: